/*
 * Automatic wrapping of 'wx' library for AMILab.
 * File: wrap/wx2.8//addwrap_wx.h
 * Generated by the script './parse_xml/parse_xml2.py'
 * Date: '14-12-2010'
 */

#ifndef _addwrap_wx_h_
#define _addwrap_wx_h_

#include "Variables.hpp"

void wrap_wx_classes( Variables::ptr& context);

#endif // _addwrap_wx_h_
