//#include "wrapfunction_class.h"
//#include "wrapfunctions.hpp"
#include "Variable.hpp"
#include "paramlist.h"
#include "ami_object.h"
#include "wxAmiEventHandler.h"
#include "wxPluginManager.h"
#include <wx/wx.h>
#include <wx/app.h>
#include <wx/arrstr.h>
#include <wx/artprov.h> 
#include <wx/aui/aui.h>
#include <wx/choice.h>
#include <wx/cmdline.h>
#include <wx/dir.h>
#include <wx/dynlib.h>
#include <wx/filename.h>
#include <wx/html/htmlwin.h>
#include <wx/imaglist.h>
#include <wx/listctrl.h>
#include <wx/panel.h>
#include <wx/regex.h> 
#include <wx/richtext/richtextctrl.h>
#include <wx/splitter.h>
#include <wx/stc/stc.h>
#include <wx/statline.h>
#include <wx/stattext.h>

