/*
 * Automatic wrapping of 'vtk' library for AMILab.
 * File: wrap/vtk5.6//addwrap_vtk.h
 * Generated by the script 'parse_xml/parse_xml2.py'
 * Date: '09-12-2010'
 */

#ifndef _addwrap_vtk_h_
#define _addwrap_vtk_h_

#include "Variables.hpp"

void wrap_vtk_classes( Variables::ptr& context);

#endif // _addwrap_vtk_h_
