/*
 * Automatic wrapping of 'vtk' library for AMILab.
 * File: wrap/vtk5.6//addwrap_vtk.cpp
 * Generated by the script 'parse_xml/parse_xml2.py'
 * Date: '11-12-2010'
 */

#include "addwrap_vtk.h"

// Currently 67 objects (classes,structures,typedefs,...) are wrapped 
extern void WrapClassvtk3DWidget_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkAbstractArray_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkAbstractMapper_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkAbstractMapper3D_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkAbstractTransform_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkAbstractVolumeMapper_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkActor_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkActorCollection_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkAlgorithm_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkBoxWidget_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkCamera_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkCellTypes_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkCollection_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkColorTransferFunction_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkCommand_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkDataArray_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkDataObject_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkDataSet_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkGPUVolumeRayCastMapper_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkHomogeneousTransform_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkImageData_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkImplicitFunction_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkIndent_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkIntArray_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkInteractorObserver_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkInteractorStyle_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkInteractorStyleImage_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkInteractorStyleSwitch_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkInteractorStyleTrackball_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkInteractorStyleTrackballCamera_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkLinearTransform_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkMatrix4x4_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkObject_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkObjectBase_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkOpenGLGPUVolumeRayCastMapper_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkPiecewiseFunction_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkPlanes_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkPointSet_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkPoints_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkPolyData_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkProp_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkProp3D_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkPropCollection_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkProperty_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkRenderWindow_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkRenderWindowInteractor_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkRenderer_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkRendererCollection_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkScalarsToColors_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkStdString_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkTimeStamp_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkTransform_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkUnicodeString_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkUnsignedCharArray_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkVariant_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkViewport_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkVolume_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkVolumeCollection_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkVolumeMapper_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkVolumeProperty_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkVolumeRayCastCompositeFunction_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkVolumeRayCastDynamicInfo_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkVolumeRayCastFunction_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkVolumeRayCastMapper_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkVolumeRayCastStaticInfo_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkWindow_AddStaticMethods( Variables::ptr&);
extern void WrapClassvtkWindowToImageFilter_AddStaticMethods( Variables::ptr&);

/*
 * Adding all the wrapped classes to the library context.
 * @param context the library context.
 */
void wrap_vtk_classes( Variables::ptr& context)
{


  WrapClassvtk3DWidget_AddStaticMethods( context);
  WrapClassvtkAbstractArray_AddStaticMethods( context);
  WrapClassvtkAbstractMapper_AddStaticMethods( context);
  WrapClassvtkAbstractMapper3D_AddStaticMethods( context);
  WrapClassvtkAbstractTransform_AddStaticMethods( context);
  WrapClassvtkAbstractVolumeMapper_AddStaticMethods( context);
  WrapClassvtkActor_AddStaticMethods( context);
  WrapClassvtkActorCollection_AddStaticMethods( context);
  WrapClassvtkAlgorithm_AddStaticMethods( context);
  WrapClassvtkBoxWidget_AddStaticMethods( context);
  WrapClassvtkCamera_AddStaticMethods( context);
  WrapClassvtkCellTypes_AddStaticMethods( context);
  WrapClassvtkCollection_AddStaticMethods( context);
  WrapClassvtkColorTransferFunction_AddStaticMethods( context);
  WrapClassvtkCommand_AddStaticMethods( context);
  WrapClassvtkDataArray_AddStaticMethods( context);
  WrapClassvtkDataObject_AddStaticMethods( context);
  WrapClassvtkDataSet_AddStaticMethods( context);
  WrapClassvtkGPUVolumeRayCastMapper_AddStaticMethods( context);
  WrapClassvtkHomogeneousTransform_AddStaticMethods( context);
  WrapClassvtkImageData_AddStaticMethods( context);
  WrapClassvtkImplicitFunction_AddStaticMethods( context);
  WrapClassvtkIndent_AddStaticMethods( context);
  WrapClassvtkIntArray_AddStaticMethods( context);
  WrapClassvtkInteractorObserver_AddStaticMethods( context);
  WrapClassvtkInteractorStyle_AddStaticMethods( context);
  WrapClassvtkInteractorStyleImage_AddStaticMethods( context);
  WrapClassvtkInteractorStyleSwitch_AddStaticMethods( context);
  WrapClassvtkInteractorStyleTrackball_AddStaticMethods( context);
  WrapClassvtkInteractorStyleTrackballCamera_AddStaticMethods( context);
  WrapClassvtkLinearTransform_AddStaticMethods( context);
  WrapClassvtkMatrix4x4_AddStaticMethods( context);
  WrapClassvtkObject_AddStaticMethods( context);
  WrapClassvtkObjectBase_AddStaticMethods( context);
  WrapClassvtkOpenGLGPUVolumeRayCastMapper_AddStaticMethods( context);
  WrapClassvtkPiecewiseFunction_AddStaticMethods( context);
  WrapClassvtkPlanes_AddStaticMethods( context);
  WrapClassvtkPointSet_AddStaticMethods( context);
  WrapClassvtkPoints_AddStaticMethods( context);
  WrapClassvtkPolyData_AddStaticMethods( context);
  WrapClassvtkProp_AddStaticMethods( context);
  WrapClassvtkProp3D_AddStaticMethods( context);
  WrapClassvtkPropCollection_AddStaticMethods( context);
  WrapClassvtkProperty_AddStaticMethods( context);
  WrapClassvtkRenderWindow_AddStaticMethods( context);
  WrapClassvtkRenderWindowInteractor_AddStaticMethods( context);
  WrapClassvtkRenderer_AddStaticMethods( context);
  WrapClassvtkRendererCollection_AddStaticMethods( context);
  WrapClassvtkScalarsToColors_AddStaticMethods( context);
  WrapClassvtkStdString_AddStaticMethods( context);
  WrapClassvtkTimeStamp_AddStaticMethods( context);
  WrapClassvtkTransform_AddStaticMethods( context);
  WrapClassvtkUnicodeString_AddStaticMethods( context);
  WrapClassvtkUnsignedCharArray_AddStaticMethods( context);
  WrapClassvtkVariant_AddStaticMethods( context);
  WrapClassvtkViewport_AddStaticMethods( context);
  WrapClassvtkVolume_AddStaticMethods( context);
  WrapClassvtkVolumeCollection_AddStaticMethods( context);
  WrapClassvtkVolumeMapper_AddStaticMethods( context);
  WrapClassvtkVolumeProperty_AddStaticMethods( context);
  WrapClassvtkVolumeRayCastCompositeFunction_AddStaticMethods( context);
  WrapClassvtkVolumeRayCastDynamicInfo_AddStaticMethods( context);
  WrapClassvtkVolumeRayCastFunction_AddStaticMethods( context);
  WrapClassvtkVolumeRayCastMapper_AddStaticMethods( context);
  WrapClassvtkVolumeRayCastStaticInfo_AddStaticMethods( context);
  WrapClassvtkWindow_AddStaticMethods( context);
  WrapClassvtkWindowToImageFilter_AddStaticMethods( context);


  #define ADD_VTK_ENUMVAL(enum,name,val) \
    {\
    BasicVariable::ptr var = AMILabType<int >::CreateVar(val);\
    if (var.get()) {\
      var->Rename(#name);\
       obj_##enum->GetContext()->AddVar(var,obj_##enum->GetContext());\
    }}

  #undef ADD_VTK_ENUMVAL
}

