
// several defines of VTK configuration
#include <vtkToolkits.h>

#include <vtkActor2D.h>
#include <vtkActorCollection.h>
#include <vtkAlgorithm.h>
#include <vtkAlgorithmOutput.h>
#include "vtkAmiCommand.h"
#include <vtkAnnotatedCubeActor.h>
#include <vtkAppendPolyData.h>
#include <vtkArrowSource.h>
#include <vtkAxesActor.h>
#include <vtkAxis.h>
#include <vtkAxisActor.h>
#include <vtkBMPReader.h>
#include <vtkBoxWidget.h>
#include <vtkBrush.h>
#include <vtkCamera.h>
#include <vtkCameraInterpolator.h>
#include <vtkCellArray.h>
#include <vtkCellData.h>
#include <vtkCell.h>
#include <vtkCellPicker.h>
#include <vtkChartXY.h>
#include <vtkCleanPolyData.h>
#include <vtkColorTransferFunction.h>
#include <vtkCommand.h>
#include <vtkConeSource.h>
#include <vtkContext2D.h>
#include <vtkContextScene.h>
#include <vtkContextView.h>
#include <vtkCoordinate.h>
#include <vtkCoordinate.h>
#include <vtkCornerAnnotation.h>
#include <vtkCubeAxesActor.h>
#include <vtkCursor3D.h>
#include <vtkDICOMImageReader.h>
#include <vtkDirectory.h>
#include <vtkDoubleArray.h>
#include <vtkElevationFilter.h>
#include <vtkFieldData.h>
#include <vtkFixedPointVolumeRayCastMapper.h>
#include <vtkFloatArray.h>
#include <vtkGlyph3D.h>

#ifdef VTK_USE_GL2PS
  // should be in a module??
  #include <vtkGL2PSExporter.h>
#endif

#include <vtkGPUInfo.h>
#include <vtkGPUInfoList.h>
#include <vtkGPUVolumeRayCastMapper.h>
#include <vtkImageData.h>
#include <vtkImageFFT.h>
#include <vtkImageFourierCenter.h>
#include <vtkImageHSIToRGB.h>
#include <vtkImageHSVToRGB.h>
#include <vtkImagePlaneWidget.h>
#include <vtkImageReader2Factory.h>
#include <vtkImageReader2.h>
#include <vtkImageResample.h>
#include <vtkImageRFFT.h>
#include <vtkImageRGBToHSI.h>
#include <vtkImageRGBToHSV.h>
#include <vtkImageViewer.h>
#include <vtkInformation.h>
#include <vtkInteractorStyleImage.h>
#include <vtkInteractorStyleTrackball.h>
#include <vtkJPEGReader.h>
#include <vtkLight.h>
#include <vtkLightCollection.h>
#include <vtkLODActor.h>
#include <vtkLookupTable.h>
#include <vtkOpenGLGPUVolumeRayCastMapper.h>
#include <vtkOrientationMarkerWidget.h>
#include <vtkOutlineFilter.h>
#include <vtkParametricSpline.h>
#include <vtkPen.h>
#include <vtkPicker.h>
#include <vtkPiecewiseFunction.h>
#include <vtkPlanes.h>
#include <vtkPlaneSource.h>
#include <vtkPlot.h>
#include <vtkPointData.h>
#include <vtkPointWidget.h>
#include <vtkPolyData.h>
#include <vtkPolyDataConnectivityFilter.h>
#include <vtkPolyDataMapper.h>
#include <vtkPolyDataNormals.h>
#include <vtkProperty.h>
#include <vtkProperty2D.h>
#include <vtkRendererCollection.h>
#include <vtkRenderer.h>
#include <vtkRenderWindow.h>
#include <vtkRenderWindowInteractor.h>
#include <vtkScalarBarActor.h>
#include <vtkSliderWidget.h>
#include <vtkSliderRepresentation2D.h>
#include <vtkSliderRepresentation3D.h>
#include <vtkSphereSource.h>
#include <vtkTable.h>
#include <vtkTextActor.h>
#include <vtkTextMapper.h>
#include <vtkTextProperty.h>
#include <vtkTexturedSphereSource.h>
#include <vtkTexture.h>
#include <vtkTransform.h>
#include <vtkIdTypeArray.h>
#include <vtkUnstructuredGridVolumeRayCastMapper.h>
#include <vtkVersion.h>
#include <vtkVolume.h>
#include <vtkVolumeCollection.h>
#include <vtkVolumeProperty.h>
#include <vtkVolumeRayCastCompositeFunction.h> 
#include <vtkVolumeRayCastMapper.h>
#include <vtkWindowToImageFilter.h>
#include <vtkXYPlotActor.h>
#include <vtkXYPlotWidget.h>
