# - Find the OpticFlow library
# defined OPTICFLOW_INCLUDE_DIRS
#
#


#
# Find the header file
#
FIND_PATH(OPTICFLOW_INCLUDE_DIR OpticalFlow/optic_flow.h)

#
# Find the library
#


INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpticFlow DEFAULT_MSG
     AMIFLUID_INCLUDE_DIR)

IF(OPTICFLOW_INCLUDE_DIR )
    SET(OPTICFLOW_INCLUDE_DIRS ${OPTICFLOW_INCLUDE_DIR})
ENDIF(OPTICFLOW_INCLUDE_DIR)

#MARK_AS_ADVANCED(AMIFLUID_INCLUDE_DIR)
#MARK_AS_ADVANCED(AMIFLUID_LIBRARY)
